apiVersion: v1
kind: Secret
metadata:
  name: harbor
data:
  .dockerconfigjson: ${DOCKER_CFG_DATA}
type: kubernetes.io/dockerconfigjson
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: project-env
data:
  NACOS_SERVER_ADDR: 10.0.11.21:8848
  NACOS_NAMESPACE: public
  NACOS_GROUP: DEFAULT_GROUP
  SENTINEL_TRANSPORT_DASHBOARD: "sentinel-dashboard:8710"
  JAVA_TOOL_OPTIONS: -javaagent:/usr/skywalking/agent/skywalking-agent.jar
  SW_AGENT_COLLECTOR_BACKEND_SERVICES: 10.0.11.21:11800
  SW_GRPC_LOG_SERVER_HOST: 10.0.11.21
  SW_GRPC_LOG_SERVER_PORT: "11800"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stl-cloud-abc-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stl-cloud-abc-backend
  template:
    metadata:
      labels:
        app: stl-cloud-abc-backend
    spec:
      initContainers:
        - name: skywalking-agent-sidecar
          image: s1:5000/apache/skywalking-agent-sidecar:8.7.0
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: sw-agent
              mountPath: /skywalking/agent
          command: ["/bin/sh", "-c", "mkdir -p /skywalking/agent && cp -r /usr/skywalking/agent/* /skywalking/agent"]
      containers:
        - name: stl-cloud-abc-backend
          image: s1:5000/dev/stl-cloud-abc-backend:latest
          imagePullPolicy: Always
          volumeMounts:
            - name: sw-agent
              mountPath: /usr/skywalking/agent
          envFrom:
            - configMapRef:
                name: project-env
          env:
            - name: SW_AGENT_NAME
              value: stl-cloud-abc-backend
          ports:
            - containerPort: 8100
      volumes:
        - name: sw-agent
          emptyDir: {}
      imagePullSecrets:
        - name: harbor
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stl-cloud-client-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stl-cloud-client-backend
  template:
    metadata:
      labels:
        app: stl-cloud-client-backend
    spec:
      initContainers:
        - name: skywalking-agent-sidecar
          image: s1:5000/apache/skywalking-agent-sidecar:8.7.0
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: sw-agent
              mountPath: /skywalking/agent
          command: ["/bin/sh", "-c", "mkdir -p /skywalking/agent && cp -r /usr/skywalking/agent/* /skywalking/agent"]
      containers:
        - name: stl-cloud-client-backend
          image: s1:5000/dev/stl-cloud-client-backend:latest
          imagePullPolicy: Always
          volumeMounts:
            - name: sw-agent
              mountPath: /usr/skywalking/agent
          envFrom:
            - configMapRef:
                name: project-env
          env:
            - name: SW_AGENT_NAME
              value: sstl-cloud-client-backend
          ports:
            - containerPort: 8200
      volumes:
        - name: sw-agent
          emptyDir: {}
      imagePullSecrets:
        - name: harbor
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stl-cloud-gateway-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stl-cloud-gateway-backend
  template:
    metadata:
      labels:
        app: stl-cloud-gateway-backend
    spec:
      initContainers:
        - name: skywalking-agent-sidecar
          image: s1:5000/apache/skywalking-agent-sidecar:8.7.0
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: sw-agent
              mountPath: /skywalking/agent
          command: ["/bin/sh", "-c", "mkdir -p /skywalking/agent && cp -r /usr/skywalking/agent/* /skywalking/agent"]
      containers:
        - name: stl-cloud-client-backend
          image: s1:5000/dev/stl-cloud-gateway-backend:latest
          imagePullPolicy: Always
          volumeMounts:
            - name: sw-agent
              mountPath: /usr/skywalking/agent
          envFrom:
            - configMapRef:
                name: project-env
          env:
            - name: SW_AGENT_NAME
              value: sstl-cloud-client-backend
          ports:
            - containerPort: 8000
      volumes:
        - name: sw-agent
          emptyDir: {}
      imagePullSecrets:
        - name: harbor
---
apiVersion: v1
kind: Service
metadata:
  name: stl-cloud-gateway-backend
spec:
  selector:
    app: stl-cloud-gateway-backend
  type: NodePort
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      nodePort: 30800
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-frontend
  labels:
    app: hello-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-frontend
  template:
    metadata:
      labels:
        app: hello-frontend
    spec:
      containers:
        - name: hello-frontend
          image: s1:5000/dev/hello-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: harbor
---
apiVersion: v1
kind: Service
metadata:
  name: hello-frontend
spec:
  selector:
    app: hello-frontend
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 30900
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-project
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "2048M"
spec:
  rules:
    - host: hello-project.custom
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: stl-cloud-gateway-backend
                port:
                  number: 8000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hello-frontend
                port:
                  number: 80
